---
  - name: start nginx
    service:
      name: "nginx"
      state: started
      enabled: yes

  - name: restart nginx
    service:
      name: "nginx"
      state: restarted
      enabled: yes

  - name: stopped nginx
    service:
      name: "nginx"
      state: stopped
      enabled: yes
