---
- name: Ensures syslog server is installed
  package:
    name: "syslog-ng"
    state: present
  tags:
    - syslog
    - syslog-client

- name: Custom everything log
  template:
    src: "{{ item }}"
    dest: "/etc/syslog-ng/conf.d/{{ item }}"
  with_items:
    - "01-graylog.conf"
  notify:
    - restart syslog-ng
  tags:
    - syslog
    - syslog-client
    - syslog-config
    - syslog-client-config
