---

- name: Ensures mysql users exists for replication
  mysql_user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    priv: "{{ item.value.grant}}" #*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT
    host: "{{ item.value.host }}"
    state: present
  with_dict: "{{ deploy_mysql_user }}"
  tags:
    - deploy
