---
#dns_allow_recursion_ip: "10.0.0.0/8;"

dns_zone_files:
  e211.db:
    dbname: "e211.db"
    type: "master"
    zonename: "e211"
#    master: "x.x.x.x"
#  taizhong.e211.db:
#    dbname: "taizhong.e211.db"
#    type: "master"
#    zonename: "taizhong.e211"

dns_forwarder_zones:
  test zone:
    domain: "test.henriksen"
    forwarders:
      - "1.1.1.1"
      - "2.2.2.2"
  taizhong dot ding:
    domain: "taizhong.ding"
    forwarders:
      - "192.168.1.109"
