---

deploy_mysql_user:
  clustercheckuser:
    password: "clustercheckpassword!"
    grant: "*.*:process"
    host: "localhost"
  wp101ansible:
    password: "wp101ansible!"
    grant: "wp101ansible.*:all"
    host: "10.100.51.%"
  wp101dk:
    password: "wp101dk!"
    grant: "wp101dk.*:all"
    host: "10.100.51.%"
  wp101intra:
    password: "wp101intra!"
    grant: "wp101intra.*:all"
    host: "10.100.51.%"

