---
php_pools:
  yourls:
    pm: "ondemand"
    max_children: "10"
    process_idle_timeout: "10s"
    max_requests: "200"
  nextcloud:
    pm: "ondemand"
    max_children: "10"
    process_idle_timeout: "10s"
    max_requests: "200"
  wp101:
    pm: "ondemand"
    max_children: "10"
    process_idle_timeout: "10s"
    max_requests: "200"
