---
- name: Ensures apache2 is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apache2"
  tags:
    - apache2

- name: Ensueres config and enabled is synced
  synchronize:
    src: "{{ item }}/"
    dest: "/etc/apache2/{{ item }}"
    owner: no
    group: no
  with_items:
    - "conf-available"
    - "conf-enabled"
  notify:
    - "restart apache2"
  tags:
    - apache2
    - apache2-config

- name: Ensures /var/www/vhosts exists
  file:
    state: "directory"
    path: "/var/www/vhosts"
    owner: "www-data"
    group: "www-data"
  tags:
    - apache2

- name: Ensures apache modules are loaded
  apache2_module:
    name: "{{ item }}"
  with_items:
    - expires
    - headers
    - rewrite
    - proxy
    - proxy_http
    - proxy_fcgi
    - authz_groupfile
  notify:
    - "restart apache2"
  tags:
    - apache2
    - apache2-config

- name: Ensures /var/www/html exists
  file:
    path: "/var/www/html"
    state: directory
    owner: "www-data"
    group: "www-data"
  tags:
    - apache2

- name: Ensures /var/www/virtual exists
  file:
    path: "/var/www/virtual"
    state: directory
    owner: "www-data"
    group: "www-data"
  tags:
    - apache2

- name: Ensures /var/www/vhosts exists
  file:
    path: "/var/www/vhosts"
    state: directory
    owner: "www-data"
    group: "www-data"
  tags:
    - apache2

- name: Ensures hc.html is synced
  template:
    src: "hc.html"
    dest: /var/www/html/hc.html
  tags:
    - apache2
    - apache2-config

- name: Ensures default index.html is present
  template:
    src: "www/index.html.j2"
    dest: "/var/www/html/index.html"
  tags:
    - apache2
    - apache2-config

- name: Ensures server signature is disabled part 1
  lineinfile:
    dest: /etc/apache2/conf-available/security.conf
    state: absent
    regexp: '^ServerSignature On'
  notify:
    - "restart apache2"
  tags:
    - apache2
    - apache2-config

- name: Ensures server signature is disabled part 2
  lineinfile:
    dest: /etc/apache2/conf-available/security.conf
    state: present
    regexp: '^ServerSignature Off'
    line: "ServerSignature Off" 
  notify:
    - "restart apache2"
  tags:
    - apache2
    - apache2-config

- name: Ensures logrote is configured
  lineinfile:
    dest: "/etc/logrotate.d/apache2"
    regexp: '^\s+rotate\s+\d+$'
    line: "	rotate {{ web_logrotate_rotate }}"
  tags:
    - apache2
    - apache2-config

- name: Ensures logfiles for apache has correct permissions
  lineinfile:
    dest: "/etc/logrotate.d/apache2"
    regexp: '^.+create'
    line: '        create 644 root www-data'
    state: present
  tags:
    - apache2
    - apache2-config
