---
- name: Ensures nginx is presnet
  package:
    name: "nginx"
    state: present
  tags:
    - nginx

- name: Ensures conf.d configs is up to date
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item.key }}.conf"
  with_dict: "{{ nginx_config }}"
  notify:
    - restart nginx
  tags:
    - nginx
    - nginx-config

