---
- name: Ensures keepalived and depencies is installed
  package:
    name: "{{ item }}"
  with_items:
    - "keepalived"
    - "psmisc"
  register: keepalived_config
  tags:
    - keepalived

- name: Ensures keepalived config is updated
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
  register: keepalived_config
  tags:
    - keepalived
    - keepalived-config

- name: Ensures keepalived is restarted
  service:
    name: "keepalived"
    state: restarted
  when: keepalived_config|changed
