---
- name: Ensures nfs-common is installed to support NFS
  apt:
    pkg: "nfs-common"
    state: present
  tags:
    - nfs
    - deploy

- name: Ensures mount folder is in place
  file:
    dest: "/mnt/web"
    state: directory
  tags:
    - nfs
    - deploy

- name: Ensures autofs is in place for auto mounting
  apt:
    pkg: "autofs"
    state: present
  tags:
    - nfs
    - deploy

- name: Set fact used in the templates for autofs
  set_fact:
    nfs_dict: "{{ nfs_mounts }}"
  tags:
    - nfs
    - deploy

- name: Ensures autofs configs is in place is in place
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
  with_list: "{{ nfs_files }}"
  register: autofs_update
  tags:
    - nfs
    - deploy

- name: Ensures autofs is reload
  service:
    name: "autofs"
    state: reloaded
  when: autofs_update|changed
  tags:
    - nfs
    - deploy

- name: Ensures nfs folders is created so i can be symlinked
  file:
    dest: "/mnt/web/nfs/{{ item }}"
    state: directory
  with_items: "{{ nfs_folder_list }}"
  tags:
    - nfs
    - deploy

- name: Ensures symlink is in place
  file:
    src: "/mnt/web/nfs/{{ item }}"
    dest: "/var/www/virtual/{{ item }}"
    owner: "www-data"
    group: "www-data"
    state: link
  with_items: "{{ nfs_folder_list }}"
  tags:
    - nfs
    - deploy
