---
- name: Ensures hostname is set to ansible_inventory
  hostname:
    name: "{{ host_fqdn }}"
  tags:
    - hostname

- sysctl:
    name: "kernel.hostname"
    value: "{{ host_fqdn }}"
    state: present
  tags:
    - hostname

- name: Ensures hosts file is added
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: 0644
  tags:
    - hosts
    - hosts-config
