---
- name: Ensures php7 and packages is installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-cli
    - php7.0-mysql
    - php7.0-curl
    - php7.0-gd
    - php7.0-json
    - php7.0-curl
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-mcrypt
    - php-imagick
    - php7.0-xml
    - php7.0-zip
    - php7.0-bz2
  tags:
    - web
    - php

